function [videos_list] = get_videos_list(training)

if training
    videos_list = {...
    'Hang';...
    'Land'};
else
videos_list = {...
    'Squash';...
    'KnockOver';...
    'Kick';...
    'Unhook';
    'Catch';...
    'Ripoff';...
    'Cut';...
    'Split';...
    'Break';...
    'Pop';...
    'Hit';...
    'Extinguish';...
    };
end

end