function [videos_list] = get_videos_list()

videos_list = {...
    'Squash';...
    'Catch';...
    'KnockOver';...
    'Unhook';...
    'Kick';...
    'Ripoff';...
    'Cut';...
    'Split';...
    'Break';...
    'Pop';...
    'Hit';...
    'Extinguish';...
    };

end