function [instructions, questions] = text_input(language)

switch language
    
    case 'estonian'
        
        instructions.general = {
            'Selles katses näitame sulle erinevaid videoid ning küsime nende kohta küsimusi.' 
            'Näitame sulle iga küsimust alati kaks korda: korra enne ja korra pärast videot.' ;...
            'Sinul on kaks ülesannet.' ;...
            'Esiteks palume sul vastata küsimusele, mis puudutab videos nähtud sündmust.' ;...
            'Teiseks palume sul määrata videos nähtud sündmuse algus- ja lõpp-punkt.' ;...
            'Alguses saad kahe videoga harjutada.' ;...
            'Kui oled valmis katset alustama, vajuta ENTER.'};
        
        instructions.boundary = {...
            'Palun märgi videol selle sündmuse algus- ja lõpp-punkt (kasuta ARVUTIHIIRT).'
            'Palun märgi esiteks alguspunkt ning seejärel lõpp-punkt.'
            'Vajuta ENTER kui sa oled valmis edasi liikuma.'};
        
        questions.agent = {'Mida POISS tegi?'};
        
        questions.neutral = {'Mis JUHTUS?'};
        
        questions.patient = {...
            'Mida ARBUUSIGA tehti?'; ...
            'Mida KOONUSEGA tehti?'; ...
            'Mida JALGPALLIGA tehti?'; ...
            'Mida VÕTMEGA tehti?'; ...
            'Mida LEHEGA tehti?'; ...
            'Mida PLAKATIGA tehti?'; ...
            };
        
        questions.instrument = {...
            'Mida NOAGA tehti?'; ...
            'Mida KIRVEGA tehti?'; ...
            'Mida VASARAGA tehti?'; ...
            'Mida NÕELAGA tehti?'; ...
            'Mida REKETIGA tehti?'; ...
            'Mida TEKIGA tehti?'; ...
            };
        
        
    case 'english'
        
        instructions.general = {...
            'You are going to see a set of videos and questions about the videos. We will always show you the question twice: before and after the video.'; ...
            'You’ll have to accomplish two tasks.'; ...
            'The first task is to answer a question based on the event shown in the video.'; ...
            'The second task is to click on the timeline to indicate the beginning and the end of the event shown in the video.'; ...
            'You will start with two practice videos'; ...
            'Click the mouse when you are ready to begin'};
        
        instructions.boundary = {'Please, mark the start point and the end point of this event on the video.'};
        
        questions.agent = {'What did the BOY do?'};
        
        questions.neutral = {'What HAPPENED?'};
        
        questions.patient = {...
            'What happened to the WATERMELON?'; ...
            'What happened to the TRAFFIC CONE?'; ...
            'What happened to the FOOTBALL?'; ...
            'What happened to the KEY?'; ...
            'What happened to the LEAF?'; ...
            'What happened to the POSTER?'...
            };
        
        questions.instrument = {...
            'What was done with the KNIFE?'; ...
            'What was done with the AXE?'; ...
            'What was done with the HAMMER?'; ...
            'What was done with the PIN?'; ...
            'What was done with the RACQUET?'; ...
            'What was done with the BLANKET?'...
            };
        
end
end