function [response_text] = type_answer(instruction_text, win, win_w, win_h, opt)

response_text = [];

dst_rect = [...
    win_w/20 - 60 ...
    win_h/4 - 60 ...
    win_w*19/20 + 60 ...
    win_h*3/4 + 60 ];

[response_text] = ...
    GetEchoString(win, instruction_text, ...
    win_w/20, win_h/4, opt.text_color, opt.background, 0, dst_rect);

ListenChar(0)

end